services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  create-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin; do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/memories --ignore-existing;
      /usr/bin/mc anonymous set public myminio/memories;
      exit 0;
      "

volumes:
  minio_data:
